### ISSUE TITLE
as的debug闪退，手动gradlew却可以

### ISSUE THREAD

**Issue by army8735** [yjy239/SkiaDemo#1]
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libskia.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.yjy.skiaapplication.SkiaUtils.<clinit>(SkiaUtils.java:17)
```
android studio无法运行，可是命令行gradlew iDebug却可以安装查看

**Comment by army8735** [comment]
```
ndk {
            abiFilters "armeabi-v7a"
        }
```
漏了这个配置，好神奇
